#pragma once

#include <windows.h>

enum class foregroundColors
{
	DXXB = FOREGROUND_BLUE,
	DXGX = FOREGROUND_GREEN,
	DXGB = FOREGROUND_GREEN | FOREGROUND_BLUE,
	DRXX = FOREGROUND_RED,
	DRXB = FOREGROUND_RED | FOREGROUND_BLUE,
	DRGX = FOREGROUND_RED | FOREGROUND_GREEN,
	DRGB = FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE,
	LXXB = FOREGROUND_INTENSITY | FOREGROUND_BLUE,
	LXGX = FOREGROUND_INTENSITY | FOREGROUND_GREEN,
	LXGB = FOREGROUND_INTENSITY | FOREGROUND_GREEN | FOREGROUND_BLUE,
	LRXX = FOREGROUND_INTENSITY | FOREGROUND_RED,
	LRXB = FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_BLUE,
	LRGX = FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_GREEN,
	LRGB = FOREGROUND_INTENSITY | FOREGROUND_RED | FOREGROUND_GREEN | FOREGROUND_BLUE
};
enum class backgroundColors
{
	DXXB = BACKGROUND_BLUE,
	DXGX = BACKGROUND_GREEN,
	DXGB = BACKGROUND_GREEN | BACKGROUND_BLUE,
	DRXX = BACKGROUND_RED,
	DRXB = BACKGROUND_RED | BACKGROUND_BLUE,
	DRGX = BACKGROUND_RED | BACKGROUND_GREEN,
	DRGB = BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE,
	LXXB = BACKGROUND_INTENSITY | BACKGROUND_BLUE,
	LXGX = BACKGROUND_INTENSITY | BACKGROUND_GREEN,
	LXGB = BACKGROUND_INTENSITY | BACKGROUND_GREEN | BACKGROUND_BLUE,
	LRXX = BACKGROUND_INTENSITY | BACKGROUND_RED,
	LRXB = BACKGROUND_INTENSITY | BACKGROUND_RED | BACKGROUND_BLUE,
	LRGX = BACKGROUND_INTENSITY | BACKGROUND_RED | BACKGROUND_GREEN,
	LRGB = BACKGROUND_INTENSITY | BACKGROUND_RED | BACKGROUND_GREEN | BACKGROUND_BLUE
};

namespace enigma_utility
{
	void getKey(int& returnValue, int& keyCode);

	void changeBackgroundColor(int& returnValue, backgroundColors color);
	void changeTextColor(int& returnValue, foregroundColors color);

	void cursorFillLevel(int& returnValue, int fillLevel);
}